### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by mnapoli** [alexandresalome/behat-launcher#3]
I had to run:

```
mkdir data/cache
chmod -R 777 data/cache
```

so that a fresh install could work (if the user running the website, e.g. Apache, is different from the logged in user).

I believe you can commit file permissions in git, so maybe you should commit a `data/cache` folder and the 777 permissions on it?

**Comment by mnapoli** [comment]
Same thing with `data/output_files`

**Comment by mnapoli** [comment]
Actually, the problem with `data/output_files` is that I run the "runner" from CLI, which means the user of the process is me. All files generated will be restricted to read to my user account.

Now Apache wants to display the log of the Behat run, and cannot read those files because it runs with `www-data`.

So everytime I run a new test, I have to run `chmod -R 777 data/output_files` so that Apache can read them.

Maybe when writing those files the PHP process could chmod them directly?

**Comment by alexandresalome** [comment]
I've added `umask(0000)` at the beginning of every entry point. Please confirm "it works".

Thanks in advance,
Alexandre

**Comment by mnapoli** [comment]
Will do.

By the way I've set up the project at work and it looks amazing. It's not perfect yet to integrate it smoothly, but it's a very promising project. I've launched a big ass test suite (several hours) I'll see tomorrow if it all worked correctly.

**Comment by mnapoli** [comment]
Works!

FYI the whole test suite ran perfectly. I confirm this is awesome :)
