### ISSUE TITLE
[RFC] Add launcher for PHPSpec 

### ISSUE THREAD

**Issue by pilot** [alexandresalome/behat-launcher#4]
Behat and PHPSpec (http://www.phpspec.net/) is closes tools, would be a good to have both on board.

**Comment by alexandresalome** [comment]
It might extend to PHPUnit, atoum, and potentially "anything you want".

Thanks for reporting

**Comment by pilot** [comment]
good to know :+1:

**Comment by alexandresalome** [comment]
Additional cases:
- Behat
- PHPUnit
- Atoum
- PHPSpec
- Symfony2 commands
- Composer
- Custom commands

It's clearly the direction Behat-Launcher will take.

I will need time to make it possible, and usable.
