### ISSUE TITLE
Configuration: operations to execute before launching a test

### ISSUE THREAD

**Issue by mnapoli** [alexandresalome/behat-launcher#7]
That would be useful if we could configure some operations to run before the tests, like pulling the git repository, generating the test database (i.e. run a shell script).

**Comment by alexandresalome** [comment]
It's very difficult here to state if it should be executed before each unit or before the test suite.

Additional examples:
- Composer commands
- Symfony2 commands
- Custom commands

We might add custom commands to project:

```
 $project
     ->addCommand('Reset', './reset.sh')
     ->addCommand('Composer install', 'composer install')
 ;
```

This would create buttons on project list.
